'use strict';

/**
 * lei-coroutine tests
 *
 * @author Zongmin Lei <leizongmin@gmail.com>
 */

const expect = require('chai').expect;
const coroutine = require('../');

describe('lei-coroutine - biantai', function () {

  it('wrap biantai function #1', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* (){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('');
    expect(fn.length).to.equal(0);
  });

  it('wrap biantai function #2', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* (a){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('');
    expect(fn.length).to.equal(1);
  });

  it('wrap biantai function #3', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* (a, b){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('');
    expect(fn.length).to.equal(2);
  });

  it('wrap biantai function #4', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* a(){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('a');
    expect(fn.length).to.equal(0);
  });

  it('wrap biantai function #5', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* aa (){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('aa');
    expect(fn.length).to.equal(0);
  });

  it('wrap biantai function #6', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* a(a, b){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('a');
    expect(fn.length).to.equal(2);
  });

  it('wrap biantai function #7', function () {
    // eslint-disable-next-line
    const fn = coroutine.wrap(function* xxx(xx,yy,zz){__cov__t5rlcGY5g_eTGwX0OB$IA.f['3']++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['11']++;let data=yield UserModel.findOneCache({phone:req.body.phone});__cov__t5rlcGY5g_eTGwX0OB$IA.s['12']++;if(!_.isEmpty(data)){__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['13']++;data.is_new_user=false;__cov__t5rlcGY5g_eTGwX0OB$IA.s['14']++;return data;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['1'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['15']++;const userInfo={phone:req.body.phone,uid:req.body.group_id,avatar:req.body.avatar,nickname:req.body.nickname,gender:req.body.gender,address:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][0]++,req.body.address)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['2'][1]++,''),location:(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][0]++,req.body.location)||(__cov__t5rlcGY5g_eTGwX0OB$IA.b['3'][1]++,[]),access_token:mongoose.Types.ObjectId()+':'+Date.now(),last_login_time:Date.now(),last_login_ip:req.ip};__cov__t5rlcGY5g_eTGwX0OB$IA.s['16']++;if(req.body.constellation){__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['17']++;userInfo.constellation=req.body.constellation;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['4'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['18']++;if(req.body.birthday){__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][0]++;__cov__t5rlcGY5g_eTGwX0OB$IA.s['19']++;userInfo.birthday=req.body.birthday;}else{__cov__t5rlcGY5g_eTGwX0OB$IA.b['5'][1]++;}__cov__t5rlcGY5g_eTGwX0OB$IA.s['20']++;data=yield new UserModel(userInfo).save();__cov__t5rlcGY5g_eTGwX0OB$IA.s['21']++;data=data.toJSON();__cov__t5rlcGY5g_eTGwX0OB$IA.s['22']++;data.is_new_user=true;__cov__t5rlcGY5g_eTGwX0OB$IA.s['23']++;return data;});
    expect(fn.name).to.equal('xxx');
    expect(fn.length).to.equal(3);
  });

});
